version: "3"

services:
  app:
    build:
      context: .
    ports:
      - "5000:5000"
    volumes:
      - ./:/andela-football-league
    command: >
      sh -c "gunicorn manage:app --bind 0.0.0.0:$PORT --reload" # sh -c "python manage.py runserver"
    environment:
      - DB_HOST=db
      - DB_NAME=$DB_NAME
      - DB_USER=$DB_USER
      - DB_PASS=$DB_PASS
      - DB_PORT=$DB_PORT
      - DEBUG=$DEBUG
      - APP_SETTINGS=$APP_SETTINGS
    depends_on:
      - db
  
  db:
    image: postgres:10-alpine
    environment:
      - POSTGRES_DB=$DB_NAME
      - POSTGRES_USER=$DB_USER
      - POSTGRES_PASSWORD=$DB_PASS