"""empty message

Revision ID: 0489a7625c4d
Revises: edb058025f81
Create Date: 2019-05-12 15:43:19.233846

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0489a7625c4d'
down_revision = 'edb058025f81'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('role',
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('role_name', sa.String(length=50), nullable=False),
    sa.Column('permission_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['permission_id'], ['permission.permission_id'], ),
    sa.PrimaryKeyConstraint('role_id')
    )
    op.create_table('access',
    sa.Column('person_id', sa.Integer(), nullable=True),
    sa.Column('permission_id', sa.Integer(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['permission_id'], ['permission.permission_id'], ),
    sa.ForeignKeyConstraint(['person_id'], ['person.person_id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['role.role_id'], )
    )
    op.add_column('person', sa.Column('active', sa.Boolean(), nullable=True))
    op.add_column('person', sa.Column('email', sa.String(length=50), nullable=False))
    op.add_column('person', sa.Column('name', sa.String(length=50), nullable=False))
    op.add_column('person', sa.Column('picture', sa.String(length=255), nullable=True))
    op.alter_column('person', 'team_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('person', 'position')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('person', sa.Column('position', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.alter_column('person', 'team_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('person', 'picture')
    op.drop_column('person', 'name')
    op.drop_column('person', 'email')
    op.drop_column('person', 'active')
    op.drop_table('access')
    op.drop_table('role')
    # ### end Alembic commands ###
