"""empty message

Revision ID: 93bea58aff7c
Revises: 0489a7625c4d
Create Date: 2019-07-30 13:51:39.189423

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93bea58aff7c'
down_revision = '0489a7625c4d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('person', sa.Column('nick_name', sa.String(length=50), nullable=True))
    op.drop_column('person', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('person', sa.Column('name', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.drop_column('person', 'nick_name')
    # ### end Alembic commands ###
