"""empty message

Revision ID: a0089a928d64
Revises: 6c1b0006e18f
Create Date: 2019-04-20 05:55:01.335279

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "a0089a928d64"
down_revision = "6c1b0006e18f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "person_profile",
        sa.Column("profile_id", sa.Integer(), nullable=False),
        sa.Column("nickname", sa.Integer(), nullable=True),
        sa.Column("position", sa.String(length=50), nullable=True),
        sa.Column("person", sa.Integer(), nullable=False),
        sa.Column("team_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["person"], ["person.person_id"]),
        sa.ForeignKeyConstraint(["team_id"], ["team.team_id"]),
        sa.PrimaryKeyConstraint("profile_id"),
    )
    op.add_column("person", sa.Column("active", sa.Boolean(), nullable=True))
    op.add_column("person", sa.Column("email", sa.String(length=50), nullable=False))
    op.add_column("person", sa.Column("name", sa.String(length=50), nullable=False))
    op.add_column("person", sa.Column("picture", sa.String(length=255), nullable=True))
    op.alter_column("person", "team_id", existing_type=sa.INTEGER(), nullable=True)
    op.drop_column("person", "position")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "person",
        sa.Column(
            "position", sa.VARCHAR(length=50), autoincrement=False, nullable=True
        ),
    )
    op.alter_column("person", "team_id", existing_type=sa.INTEGER(), nullable=False)
    op.drop_column("person", "picture")
    op.drop_column("person", "name")
    op.drop_column("person", "email")
    op.drop_column("person", "active")
    op.drop_table("person_profile")
    # ### end Alembic commands ###
