"""empty message

Revision ID: edb058025f81
Revises: 5fa860be380f
Create Date: 2019-05-09 14:51:22.024239

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'edb058025f81'
down_revision = '5fa860be380f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permission',
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.Column('permission_name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('permission_id')
    )
    # op.drop_table('person_profile')
    op.add_column('person', sa.Column('position', sa.String(length=50), nullable=True))
    op.alter_column('person', 'team_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('person', 'name')
    op.drop_column('person', 'active')
    op.drop_column('person', 'picture')
    op.drop_column('person', 'email')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('person', sa.Column('email', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('person', sa.Column('picture', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('person', sa.Column('active', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('person', sa.Column('name', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.alter_column('person', 'team_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('person', 'position')
    op.create_table('person_profile',
    sa.Column('profile_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nickname', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('position', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('team_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('person_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['person.person_id'], name='person_profile_person_id_fkey'),
    sa.ForeignKeyConstraint(['team_id'], ['team.team_id'], name='person_profile_team_id_fkey'),
    sa.PrimaryKeyConstraint('profile_id', name='person_profile_pkey')
    )
    op.drop_table('permission')
    # ### end Alembic commands ###
